# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: new_label.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fnew_label.proto\x12\tnew_label\"p\n\x06Labels\x12\x37\n\x0e\x66licker_frames\x18\x01 \x03(\x0b\x32\x1f.new_label.Labels.FlickerFrames\x1a-\n\rFlickerFrames\x12\r\n\x05video\x18\x01 \x01(\t\x12\r\n\x05\x66rame\x18\x02 \x03(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'new_label_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LABELS._serialized_start=30
  _LABELS._serialized_end=142
  _LABELS_FLICKERFRAMES._serialized_start=97
  _LABELS_FLICKERFRAMES._serialized_end=142
# @@protoc_insertion_point(module_scope)
